# Generated by Django 5.0.6 on 2024-07-11 06:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_message_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='seen_by',
            field=models.ManyToManyField(blank=True, related_name='seen_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
